// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiihcxskpszelsxluxll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaWhjeHNrcHN6ZWxzeGx1eGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTMyNzgsImV4cCI6MjA2NDY2OTI3OH0.qBSOqIzMs-yB5uFtEPdqs8FH_T7NvQIN5Kb82N5imnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);